# Generated by Django 6.0.3 on 2026-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name="user",
                    name="is_deleted",
                    field=models.BooleanField(null=True, default=None),
                ),
                migrations.AddField(
                    model_name="user",
                    name="is_operator",
                    field=models.BooleanField(null=True, default=None),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="is_deleted",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="user",
                    name="is_operator",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
