# Generated by Django 6.0.3 on 2026-03-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    # Needed for CREATE INDEX CONCURRENTLY
    atomic = False

    operations = [
        migrations.AlterField(
            model_name="submissionanswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_answers",
                to="surveys.answer",
                verbose_name="Answer",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX CONCURRENTLY "
                        "answer_question_order_unique_idx "
                        'ON surveys_answer ("question_id", "order");'
                    ),
                    reverse_sql=(
                        "DROP INDEX CONCURRENTLY answer_question_order_unique_idx;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE surveys_answer "
                        "ADD CONSTRAINT answer_question_order_unique "
                        "UNIQUE USING INDEX answer_question_order_unique_idx;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE surveys_answer "
                        "DROP CONSTRAINT answer_question_order_unique;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX CONCURRENTLY "
                        "question_survey_order_unique_idx "
                        'ON surveys_question ("survey_id", "order");'
                    ),
                    reverse_sql=(
                        "DROP INDEX CONCURRENTLY question_survey_order_unique_idx;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE surveys_question "
                        "ADD CONSTRAINT question_survey_order_unique "
                        "UNIQUE USING INDEX question_survey_order_unique_idx;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE surveys_question "
                        "DROP CONSTRAINT question_survey_order_unique;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="answer",
                    constraint=models.UniqueConstraint(
                        fields=("question", "order"),
                        name="answer_question_order_unique",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="question",
                    constraint=models.UniqueConstraint(
                        fields=("survey", "order"),
                        name="question_survey_order_unique",
                    ),
                ),
            ],
        ),
    ]
